# Generated by Django 3.2.5 on 2021-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_post', models.CharField(max_length=20)),
                ('emp_contact', models.IntegerField()),
                ('emp_salary', models.IntegerField()),
                ('emp_doj', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
