# Generated by Django 2.2.14 on 2021-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pcontact', models.IntegerField()),
            ],
            options={
                'db_table': 'tblperson',
            },
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
